# Generated by Django 5.1.7 on 2025-03-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
