# Generated by Django 5.1.7 on 2025-08-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0005_servicecategory_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory_System.office'),
        ),
    ]
