# Generated by Django 5.1.7 on 2025-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0007_servicerequest_description_servicerequest_requestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='action_taken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
