# Generated by Django 5.1.7 on 2025-08-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0008_servicerequest_action_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
