# Generated by Django 5.1.7 on 2025-08-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0009_alter_servicerequest_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='position',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
    ]
