# Generated by Django 5.1.7 on 2025-08-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0011_remove_userpermission_position_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='employee_position',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
    ]
