# Generated by Django 5.1.7 on 2025-08-20 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0012_remove_userprofile_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingErrorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('area_section', models.CharField(max_length=255)),
                ('hospital_no', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=255)),
                ('encoding_error_details', models.TextField()),
                ('correct_data_details', models.TextField()),
                ('encoded_by', models.CharField(max_length=255)),
                ('encoded_date', models.DateField(blank=True, null=True)),
                ('noted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('noted_date', models.DateField(blank=True, null=True)),
                ('corrected_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'IT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_encoding_errors', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory_System.office')),
            ],
        ),
    ]
