# Generated by Django 5.1.7 on 2025-08-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0013_encodingerrorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodingerrorrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
