# Generated by Django 5.1.7 on 2025-09-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0015_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('area_section', models.CharField(max_length=255)),
                ('details_of_request', models.TextField()),
                ('attachment', models.FileField(blank=True, help_text='Attach pictures, graphics, or other web materials', null=True, upload_to='website_uploads/')),
                ('prepared_by', models.CharField(max_length=255)),
                ('prepared_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
