# Generated by Django 5.1.7 on 2025-09-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0016_websiteuploadrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuploadrequest',
            name='attachment',
        ),
        migrations.CreateModel(
            name='WebsiteUploadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='website_uploads/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Inventory_System.websiteuploadrequest')),
            ],
        ),
    ]
