# Generated by Django 5.1.7 on 2025-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0017_remove_websiteuploadrequest_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuploadrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='websiteuploadrequest',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
