# Generated by Django 5.1.7 on 2025-09-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_System', '0018_alter_websiteuploadrequest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuploadrequest',
            name='prepared_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
